services:
  postgres:
    image: postgres:14
    container_name: postgres_prova_pratica
    volumes:
      - type: volume
        source: postgres_data
        target: /var/lib/postgresql/data
    environment:
      POSTGRES_DB: prova_pratica
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: senai
    ports:
      - "5432:5432"
volumes:
  postgres_data:
