# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import estoque_pb2 as estoque__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in estoque_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class estoqueServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.recuperarItemEstoque = channel.unary_unary(
                '/estoque.estoqueService/recuperarItemEstoque',
                request_serializer=estoque__pb2.ItemEstoqueRequest.SerializeToString,
                response_deserializer=estoque__pb2.ItemEstoqueResponse.FromString,
                _registered_method=True)
        self.atualizarItemEstoque = channel.unary_unary(
                '/estoque.estoqueService/atualizarItemEstoque',
                request_serializer=estoque__pb2.UpdateItemEstoqueRequest.SerializeToString,
                response_deserializer=estoque__pb2.ItemEstoqueResponse.FromString,
                _registered_method=True)


class estoqueServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def recuperarItemEstoque(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def atualizarItemEstoque(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_estoqueServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'recuperarItemEstoque': grpc.unary_unary_rpc_method_handler(
                    servicer.recuperarItemEstoque,
                    request_deserializer=estoque__pb2.ItemEstoqueRequest.FromString,
                    response_serializer=estoque__pb2.ItemEstoqueResponse.SerializeToString,
            ),
            'atualizarItemEstoque': grpc.unary_unary_rpc_method_handler(
                    servicer.atualizarItemEstoque,
                    request_deserializer=estoque__pb2.UpdateItemEstoqueRequest.FromString,
                    response_serializer=estoque__pb2.ItemEstoqueResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'estoque.estoqueService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('estoque.estoqueService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class estoqueService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def recuperarItemEstoque(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/estoque.estoqueService/recuperarItemEstoque',
            estoque__pb2.ItemEstoqueRequest.SerializeToString,
            estoque__pb2.ItemEstoqueResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def atualizarItemEstoque(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/estoque.estoqueService/atualizarItemEstoque',
            estoque__pb2.UpdateItemEstoqueRequest.SerializeToString,
            estoque__pb2.ItemEstoqueResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
