# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: estoque.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'estoque.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\restoque.proto\x12\x07\x65stoque\"(\n\x12ItemEstoqueRequest\x12\x12\n\ncodigoItem\x18\x01 \x01(\x05\"Q\n\x18UpdateItemEstoqueRequest\x12\x12\n\ncodigoItem\x18\x01 \x01(\x05\x12\r\n\x05valor\x18\x02 \x01(\x02\x12\x12\n\nquantidade\x18\x03 \x01(\x05\"Z\n\x13ItemEstoqueResponse\x12\x12\n\ncodigoItem\x18\x01 \x01(\x05\x12\x0c\n\x04nome\x18\x02 \x01(\t\x12\r\n\x05valor\x18\x03 \x01(\x02\x12\x12\n\nquantidade\x18\x04 \x01(\x05\x32\xbc\x01\n\x0e\x65stoqueService\x12Q\n\x14recuperarItemEstoque\x12\x1b.estoque.ItemEstoqueRequest\x1a\x1c.estoque.ItemEstoqueResponse\x12W\n\x14\x61tualizarItemEstoque\x12!.estoque.UpdateItemEstoqueRequest\x1a\x1c.estoque.ItemEstoqueResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'estoque_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ITEMESTOQUEREQUEST']._serialized_start=26
  _globals['_ITEMESTOQUEREQUEST']._serialized_end=66
  _globals['_UPDATEITEMESTOQUEREQUEST']._serialized_start=68
  _globals['_UPDATEITEMESTOQUEREQUEST']._serialized_end=149
  _globals['_ITEMESTOQUERESPONSE']._serialized_start=151
  _globals['_ITEMESTOQUERESPONSE']._serialized_end=241
  _globals['_ESTOQUESERVICE']._serialized_start=244
  _globals['_ESTOQUESERVICE']._serialized_end=432
# @@protoc_insertion_point(module_scope)
