from turtle import *
from time import sleep
pat = Turtle()
pat.shape("turtle")
pat.right(90)
pat.penup()
fonte1 = ("Comic Sans", 20, "italic")

pat.write("Curso", False, "center", fonte1)
pat.fd(40)
pat.write("de", False, "center", fonte1)
pat.fd(40)
pat.write("programa de garotos de programa", False, "center", fonte1)
pat.fd(30)
pat.pendown()
pat.fd(50)
pat.lt(90)
pat.fd(50)
pat.lt(90)
pat.fd(50)
pat.lt(90)
pat.fd(100) 
pat.fd(50)
pat.lt(90)
pat.fd(50)
pat.lt(90)
pat.fd(50)
pat.lt(90)
pat.fd(50)
pat.setpos(-300, -80)
input("Pressione Enter para fechar a janela...")